[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/data/"
  to = "/data/:splat"
  status = 200
  force = true

    [redirects.rate_limit]
    window_limit = 100
    window_size = 60
    aggregate_by = ["ip", "domain"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
