[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

    [redirects.rate_limit]
    window_limit = 20
    window_size = 600
    aggregate_by = ["ip", "domain"]

[[redirects]]
  from = "_next/images?*"
  to = "_next/images?:splat"
  status = 200
  force = true

    [redirects.rate_limit]
    window_limit = 20
    window_size = 600
    aggregate_by = ["ip", "domain"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
